apiVersion: batch/v1
kind: Job
metadata:
  name: blockchain-rust-job
spec:
  template:
    metadata:
      labels:
        app: blockchain-rust
    spec:
      restartPolicy: Never
      containers:
      - name: blockchain-rust
        image: semyo/blockchain-rust:latest
